// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator.proto

package grpc_calculator_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalculatorAddRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorAddRequest) Reset()         { *m = CalculatorAddRequest{} }
func (m *CalculatorAddRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorAddRequest) ProtoMessage()    {}
func (*CalculatorAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{0}
}

func (m *CalculatorAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorAddRequest.Unmarshal(m, b)
}
func (m *CalculatorAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorAddRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorAddRequest.Merge(m, src)
}
func (m *CalculatorAddRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorAddRequest.Size(m)
}
func (m *CalculatorAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorAddRequest proto.InternalMessageInfo

func (m *CalculatorAddRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *CalculatorAddRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type CalculatorSubRequest struct {
	C                    int32    `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	D                    int32    `protobuf:"varint,2,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorSubRequest) Reset()         { *m = CalculatorSubRequest{} }
func (m *CalculatorSubRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorSubRequest) ProtoMessage()    {}
func (*CalculatorSubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{1}
}

func (m *CalculatorSubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorSubRequest.Unmarshal(m, b)
}
func (m *CalculatorSubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorSubRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorSubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorSubRequest.Merge(m, src)
}
func (m *CalculatorSubRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorSubRequest.Size(m)
}
func (m *CalculatorSubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorSubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorSubRequest proto.InternalMessageInfo

func (m *CalculatorSubRequest) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *CalculatorSubRequest) GetD() int32 {
	if m != nil {
		return m.D
	}
	return 0
}

type CalculatorMulRequest struct {
	E                    int32    `protobuf:"varint,1,opt,name=e,proto3" json:"e,omitempty"`
	F                    int32    `protobuf:"varint,2,opt,name=f,proto3" json:"f,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorMulRequest) Reset()         { *m = CalculatorMulRequest{} }
func (m *CalculatorMulRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorMulRequest) ProtoMessage()    {}
func (*CalculatorMulRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{2}
}

func (m *CalculatorMulRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorMulRequest.Unmarshal(m, b)
}
func (m *CalculatorMulRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorMulRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorMulRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorMulRequest.Merge(m, src)
}
func (m *CalculatorMulRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorMulRequest.Size(m)
}
func (m *CalculatorMulRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorMulRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorMulRequest proto.InternalMessageInfo

func (m *CalculatorMulRequest) GetE() int32 {
	if m != nil {
		return m.E
	}
	return 0
}

func (m *CalculatorMulRequest) GetF() int32 {
	if m != nil {
		return m.F
	}
	return 0
}

type CalculatorDivRequest struct {
	M                    int32    `protobuf:"varint,1,opt,name=m,proto3" json:"m,omitempty"`
	N                    int32    `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorDivRequest) Reset()         { *m = CalculatorDivRequest{} }
func (m *CalculatorDivRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorDivRequest) ProtoMessage()    {}
func (*CalculatorDivRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{3}
}

func (m *CalculatorDivRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorDivRequest.Unmarshal(m, b)
}
func (m *CalculatorDivRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorDivRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorDivRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorDivRequest.Merge(m, src)
}
func (m *CalculatorDivRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorDivRequest.Size(m)
}
func (m *CalculatorDivRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorDivRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorDivRequest proto.InternalMessageInfo

func (m *CalculatorDivRequest) GetM() int32 {
	if m != nil {
		return m.M
	}
	return 0
}

func (m *CalculatorDivRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type CalculatorInt32Response struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorInt32Response) Reset()         { *m = CalculatorInt32Response{} }
func (m *CalculatorInt32Response) String() string { return proto.CompactTextString(m) }
func (*CalculatorInt32Response) ProtoMessage()    {}
func (*CalculatorInt32Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{4}
}

func (m *CalculatorInt32Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorInt32Response.Unmarshal(m, b)
}
func (m *CalculatorInt32Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorInt32Response.Marshal(b, m, deterministic)
}
func (m *CalculatorInt32Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorInt32Response.Merge(m, src)
}
func (m *CalculatorInt32Response) XXX_Size() int {
	return xxx_messageInfo_CalculatorInt32Response.Size(m)
}
func (m *CalculatorInt32Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorInt32Response.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorInt32Response proto.InternalMessageInfo

func (m *CalculatorInt32Response) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CalculatorFloatResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorFloatResponse) Reset()         { *m = CalculatorFloatResponse{} }
func (m *CalculatorFloatResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorFloatResponse) ProtoMessage()    {}
func (*CalculatorFloatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{5}
}

func (m *CalculatorFloatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorFloatResponse.Unmarshal(m, b)
}
func (m *CalculatorFloatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorFloatResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorFloatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorFloatResponse.Merge(m, src)
}
func (m *CalculatorFloatResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorFloatResponse.Size(m)
}
func (m *CalculatorFloatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorFloatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorFloatResponse proto.InternalMessageInfo

func (m *CalculatorFloatResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CalculatorAddRequest)(nil), "grpc.calculator.v1.CalculatorAddRequest")
	proto.RegisterType((*CalculatorSubRequest)(nil), "grpc.calculator.v1.CalculatorSubRequest")
	proto.RegisterType((*CalculatorMulRequest)(nil), "grpc.calculator.v1.CalculatorMulRequest")
	proto.RegisterType((*CalculatorDivRequest)(nil), "grpc.calculator.v1.CalculatorDivRequest")
	proto.RegisterType((*CalculatorInt32Response)(nil), "grpc.calculator.v1.CalculatorInt32Response")
	proto.RegisterType((*CalculatorFloatResponse)(nil), "grpc.calculator.v1.CalculatorFloatResponse")
}

func init() { proto.RegisterFile("calculator.proto", fileDescriptor_c686ea360062a8cf) }

var fileDescriptor_c686ea360062a8cf = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd3, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0x07, 0x70, 0xb2, 0xe1, 0x0e, 0x41, 0x50, 0x82, 0x2f, 0xc3, 0x93, 0xec, 0x34, 0x10, 0xdb,
	0x75, 0xbb, 0x78, 0xdd, 0x1c, 0x8a, 0x87, 0xc1, 0xd8, 0xc0, 0x83, 0x07, 0x47, 0xde, 0x36, 0x8b,
	0x69, 0x32, 0xdb, 0xa4, 0xe2, 0x77, 0xf0, 0x93, 0xf8, 0x29, 0x25, 0xba, 0x98, 0x06, 0xa7, 0x85,
	0x1d, 0xff, 0xa1, 0xbf, 0x7f, 0x43, 0x1e, 0x1e, 0x78, 0x48, 0xb1, 0xa0, 0x46, 0x60, 0xad, 0xf2,
	0x68, 0x9d, 0x2b, 0xad, 0x10, 0x5a, 0xe5, 0x6b, 0x1a, 0x55, 0x8e, 0xcb, 0xa4, 0xd3, 0x87, 0x47,
	0xd7, 0x3f, 0x07, 0x43, 0xc6, 0x66, 0xfc, 0xc5, 0xf0, 0x42, 0xa3, 0x7d, 0x08, 0x70, 0x1b, 0x9c,
	0x83, 0xee, 0xde, 0x0c, 0x60, 0x9b, 0x48, 0xbb, 0xf1, 0x9d, 0x48, 0x68, 0xe6, 0x86, 0x54, 0x0c,
	0x75, 0x86, 0xda, 0xc4, 0x9c, 0x61, 0xa1, 0x99, 0x18, 0x51, 0x31, 0xdc, 0x19, 0x6e, 0xd3, 0xd2,
	0x99, 0x65, 0x68, 0xc6, 0x69, 0x59, 0x31, 0x99, 0x33, 0x99, 0x4d, 0xd2, 0x19, 0xd9, 0x49, 0xe0,
	0xa9, 0x37, 0x77, 0x52, 0x0f, 0xfa, 0x33, 0x5e, 0xac, 0x95, 0x2c, 0x38, 0x3a, 0x81, 0xad, 0x9c,
	0x17, 0x46, 0xe8, 0x8d, 0xdd, 0xa4, 0x90, 0xdc, 0x08, 0x85, 0xf5, 0x1f, 0xa4, 0xe1, 0x48, 0xff,
	0xbd, 0x09, 0xa1, 0x37, 0xe8, 0x11, 0x36, 0x87, 0x8c, 0xa1, 0x6e, 0xf4, 0xfb, 0x81, 0xa3, 0x6d,
	0xaf, 0x7b, 0x76, 0xf1, 0xff, 0x97, 0xc1, 0xbd, 0x7b, 0xc0, 0xf6, 0xcf, 0x0d, 0xa9, 0xeb, 0xf7,
	0x93, 0xd8, 0xa1, 0x7f, 0x62, 0x44, 0x5d, 0xbf, 0x9f, 0xda, 0x0e, 0xfd, 0xe3, 0xb4, 0xac, 0xeb,
	0xf7, 0x13, 0xae, 0xeb, 0x0f, 0x86, 0xd4, 0x03, 0xa3, 0x37, 0x78, 0x9c, 0xaa, 0x2d, 0x64, 0x74,
	0xe0, 0xcd, 0xd4, 0xae, 0xc0, 0x14, 0x3c, 0x5c, 0xad, 0x52, 0xfd, 0x64, 0x48, 0x44, 0x55, 0x16,
	0xbf, 0x72, 0x49, 0xb1, 0x8c, 0x9f, 0x53, 0x7d, 0xc9, 0x78, 0xa6, 0x62, 0x8f, 0x63, 0x5b, 0xb6,
	0xf0, 0x79, 0x51, 0x26, 0x1f, 0x0d, 0x74, 0x6b, 0xff, 0xe0, 0x2b, 0xa3, 0xfb, 0x84, 0xb4, 0xbe,
	0x56, 0x6b, 0xf0, 0x19, 0x00, 0x00, 0xff, 0xff, 0xca, 0x13, 0x60, 0x4f, 0x6e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorClient interface {
	Add(ctx context.Context, in *CalculatorAddRequest, opts ...grpc.CallOption) (Calculator_AddClient, error)
	Sub(ctx context.Context, in *CalculatorSubRequest, opts ...grpc.CallOption) (Calculator_SubClient, error)
	Mul(ctx context.Context, in *CalculatorMulRequest, opts ...grpc.CallOption) (Calculator_MulClient, error)
	Div(ctx context.Context, in *CalculatorDivRequest, opts ...grpc.CallOption) (Calculator_DivClient, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, in *CalculatorAddRequest, opts ...grpc.CallOption) (Calculator_AddClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[0], "/grpc.calculator.v1.Calculator/Add", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorAddClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculator_AddClient interface {
	Recv() (*CalculatorInt32Response, error)
	grpc.ClientStream
}

type calculatorAddClient struct {
	grpc.ClientStream
}

func (x *calculatorAddClient) Recv() (*CalculatorInt32Response, error) {
	m := new(CalculatorInt32Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorClient) Sub(ctx context.Context, in *CalculatorSubRequest, opts ...grpc.CallOption) (Calculator_SubClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[1], "/grpc.calculator.v1.Calculator/Sub", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorSubClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculator_SubClient interface {
	Recv() (*CalculatorInt32Response, error)
	grpc.ClientStream
}

type calculatorSubClient struct {
	grpc.ClientStream
}

func (x *calculatorSubClient) Recv() (*CalculatorInt32Response, error) {
	m := new(CalculatorInt32Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorClient) Mul(ctx context.Context, in *CalculatorMulRequest, opts ...grpc.CallOption) (Calculator_MulClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[2], "/grpc.calculator.v1.Calculator/Mul", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorMulClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculator_MulClient interface {
	Recv() (*CalculatorInt32Response, error)
	grpc.ClientStream
}

type calculatorMulClient struct {
	grpc.ClientStream
}

func (x *calculatorMulClient) Recv() (*CalculatorInt32Response, error) {
	m := new(CalculatorInt32Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorClient) Div(ctx context.Context, in *CalculatorDivRequest, opts ...grpc.CallOption) (Calculator_DivClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[3], "/grpc.calculator.v1.Calculator/Div", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorDivClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculator_DivClient interface {
	Recv() (*CalculatorFloatResponse, error)
	grpc.ClientStream
}

type calculatorDivClient struct {
	grpc.ClientStream
}

func (x *calculatorDivClient) Recv() (*CalculatorFloatResponse, error) {
	m := new(CalculatorFloatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServer is the server API for Calculator service.
type CalculatorServer interface {
	Add(*CalculatorAddRequest, Calculator_AddServer) error
	Sub(*CalculatorSubRequest, Calculator_SubServer) error
	Mul(*CalculatorMulRequest, Calculator_MulServer) error
	Div(*CalculatorDivRequest, Calculator_DivServer) error
}

// UnimplementedCalculatorServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (*UnimplementedCalculatorServer) Add(req *CalculatorAddRequest, srv Calculator_AddServer) error {
	return status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCalculatorServer) Sub(req *CalculatorSubRequest, srv Calculator_SubServer) error {
	return status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (*UnimplementedCalculatorServer) Mul(req *CalculatorMulRequest, srv Calculator_MulServer) error {
	return status.Errorf(codes.Unimplemented, "method Mul not implemented")
}
func (*UnimplementedCalculatorServer) Div(req *CalculatorDivRequest, srv Calculator_DivServer) error {
	return status.Errorf(codes.Unimplemented, "method Div not implemented")
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatorAddRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).Add(m, &calculatorAddServer{stream})
}

type Calculator_AddServer interface {
	Send(*CalculatorInt32Response) error
	grpc.ServerStream
}

type calculatorAddServer struct {
	grpc.ServerStream
}

func (x *calculatorAddServer) Send(m *CalculatorInt32Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Calculator_Sub_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatorSubRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).Sub(m, &calculatorSubServer{stream})
}

type Calculator_SubServer interface {
	Send(*CalculatorInt32Response) error
	grpc.ServerStream
}

type calculatorSubServer struct {
	grpc.ServerStream
}

func (x *calculatorSubServer) Send(m *CalculatorInt32Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Calculator_Mul_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatorMulRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).Mul(m, &calculatorMulServer{stream})
}

type Calculator_MulServer interface {
	Send(*CalculatorInt32Response) error
	grpc.ServerStream
}

type calculatorMulServer struct {
	grpc.ServerStream
}

func (x *calculatorMulServer) Send(m *CalculatorInt32Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Calculator_Div_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatorDivRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).Div(m, &calculatorDivServer{stream})
}

type Calculator_DivServer interface {
	Send(*CalculatorFloatResponse) error
	grpc.ServerStream
}

type calculatorDivServer struct {
	grpc.ServerStream
}

func (x *calculatorDivServer) Send(m *CalculatorFloatResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.calculator.v1.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Add",
			Handler:       _Calculator_Add_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sub",
			Handler:       _Calculator_Sub_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Mul",
			Handler:       _Calculator_Mul_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Div",
			Handler:       _Calculator_Div_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
